/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.edu.iftm.renthub.view;

import br.edu.iftm.renthub.control.EquipamentoController;
import br.edu.iftm.renthub.model.Equipamento;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jhonn
 */
public class BuscarEquipamento extends javax.swing.JDialog {
    private UtilsComponent estilo;
    private DefaultTableModel modelo;
    private EquipamentoController  equipamentoController;
    private List<Equipamento> equipamentos;
    private Equipamento equipamento;
    private TelaPrincipal tela;
    private int identificador;
    /**
     * Creates new form BuscarEquipamento
     */
    public BuscarEquipamento(java.awt.Frame parent, boolean modal, Connection conexao, TelaPrincipal tela) throws SQLException {
        super(parent, modal);
        equipamentoController = new EquipamentoController(conexao);
        this.tela = tela;
        initComponents();
        estilo = new UtilsComponent();
        modelo = (DefaultTableModel) tbBuscaEquipamento.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnTelaBuscaEquipamento = new javax.swing.JPanel();
        lbTituloDescricao = new javax.swing.JLabel();
        tfBuscaEquipamento = new javax.swing.JTextField();
        btBuscar = new RoundedButton("");
        jScrollPane1 = new javax.swing.JScrollPane();
        tbBuscaEquipamento = new javax.swing.JTable();
        btSelecionar = new RoundedButton("");
        btLimpar = new RoundedButton("");
        btSair = new RoundedButton("");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnTelaBuscaEquipamento.setBackground(new java.awt.Color(255, 255, 255));

        lbTituloDescricao.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbTituloDescricao.setForeground(new java.awt.Color(0, 0, 0));
        lbTituloDescricao.setText("Descrição:");

        tfBuscaEquipamento.setBackground(new java.awt.Color(215, 215, 215));
        tfBuscaEquipamento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfBuscaEquipamento.setForeground(new java.awt.Color(0, 0, 0));

        btBuscar.setBackground(new java.awt.Color(240, 240, 240));
        btBuscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btBuscar.setForeground(new java.awt.Color(0, 0, 0));
        btBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loupe.png"))); // NOI18N
        btBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btBuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btBuscarMouseExited(evt);
            }
        });
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        tbBuscaEquipamento.setBackground(new java.awt.Color(215, 215, 215));
        tbBuscaEquipamento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbBuscaEquipamento.setForeground(new java.awt.Color(0, 0, 0));
        tbBuscaEquipamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Descrição", "Qtd. Disp.", "Vlr. Diario", "Vlr. Mensal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbBuscaEquipamento);
        if (tbBuscaEquipamento.getColumnModel().getColumnCount() > 0) {
            tbBuscaEquipamento.getColumnModel().getColumn(0).setPreferredWidth(30);
            tbBuscaEquipamento.getColumnModel().getColumn(1).setPreferredWidth(350);
            tbBuscaEquipamento.getColumnModel().getColumn(2).setPreferredWidth(80);
            tbBuscaEquipamento.getColumnModel().getColumn(3).setPreferredWidth(80);
            tbBuscaEquipamento.getColumnModel().getColumn(4).setPreferredWidth(80);
        }

        btSelecionar.setBackground(new java.awt.Color(240, 240, 240));
        btSelecionar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btSelecionar.setForeground(new java.awt.Color(0, 0, 0));
        btSelecionar.setText("Selecionar");
        btSelecionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btSelecionarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btSelecionarMouseExited(evt);
            }
        });
        btSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSelecionarActionPerformed(evt);
            }
        });

        btLimpar.setBackground(new java.awt.Color(240, 240, 240));
        btLimpar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btLimpar.setForeground(new java.awt.Color(0, 0, 0));
        btLimpar.setText("Limpar");
        btLimpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btLimparMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btLimparMouseExited(evt);
            }
        });
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btSair.setBackground(new java.awt.Color(240, 240, 240));
        btSair.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btSair.setForeground(new java.awt.Color(0, 0, 0));
        btSair.setText("Sair");
        btSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btSairMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btSairMouseExited(evt);
            }
        });
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnTelaBuscaEquipamentoLayout = new javax.swing.GroupLayout(pnTelaBuscaEquipamento);
        pnTelaBuscaEquipamento.setLayout(pnTelaBuscaEquipamentoLayout);
        pnTelaBuscaEquipamentoLayout.setHorizontalGroup(
            pnTelaBuscaEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTelaBuscaEquipamentoLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(pnTelaBuscaEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnTelaBuscaEquipamentoLayout.createSequentialGroup()
                        .addComponent(btSelecionar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnTelaBuscaEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(pnTelaBuscaEquipamentoLayout.createSequentialGroup()
                            .addGroup(pnTelaBuscaEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnTelaBuscaEquipamentoLayout.createSequentialGroup()
                                    .addComponent(lbTituloDescricao)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addComponent(tfBuscaEquipamento))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        pnTelaBuscaEquipamentoLayout.setVerticalGroup(
            pnTelaBuscaEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTelaBuscaEquipamentoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lbTituloDescricao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnTelaBuscaEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfBuscaEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnTelaBuscaEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSelecionar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnTelaBuscaEquipamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnTelaBuscaEquipamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btBuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btBuscarMouseEntered
        estilo.aplicaHoverEntered(btBuscar);
    }//GEN-LAST:event_btBuscarMouseEntered

    private void btBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btBuscarMouseExited
        estilo.aplicaHoverExited(btBuscar);
    }//GEN-LAST:event_btBuscarMouseExited

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        String descricao = tfBuscaEquipamento.getText();
        equipamentos = equipamentoController.listar(descricao);
        modelo.setRowCount(0);
        for (Equipamento equip : equipamentos){
            Object[] linha = { equip.getId(), equip.getDescricao(), equip.getQtdDisponivel(), equip.getVlrDiaria(), equip.getVlrMensal()};
            modelo.addRow(linha);
        }
    }//GEN-LAST:event_btBuscarActionPerformed

    private void btSelecionarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSelecionarMouseEntered
        estilo.aplicaHoverEntered(btSelecionar);
    }//GEN-LAST:event_btSelecionarMouseEntered

    private void btSelecionarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSelecionarMouseExited
        estilo.aplicaHoverExited(btSelecionar);
    }//GEN-LAST:event_btSelecionarMouseExited

    private void btLimparMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btLimparMouseEntered
        estilo.aplicaHoverEntered(btLimpar);
    }//GEN-LAST:event_btLimparMouseEntered

    private void btLimparMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btLimparMouseExited
        estilo.aplicaHoverExited(btLimpar);
    }//GEN-LAST:event_btLimparMouseExited

    private void btSairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSairMouseEntered
        estilo.aplicaHoverEntered(btSair);
    }//GEN-LAST:event_btSairMouseEntered

    private void btSairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSairMouseExited
        estilo.aplicaHoverExited(btSair);
    }//GEN-LAST:event_btSairMouseExited

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        limpaBuscarEquipamento();
        dispose();
    }//GEN-LAST:event_btSairActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limpaBuscarEquipamento();
    }//GEN-LAST:event_btLimparActionPerformed

    private void btSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSelecionarActionPerformed
        int indiceTabela = tbBuscaEquipamento.getSelectedRow();
        if(indiceTabela == -1){
            JOptionPane.showMessageDialog(rootPane, "Selecione um equipamento!", "Busca de equipamento", JOptionPane.WARNING_MESSAGE);
            return;
        }else{
            equipamento = equipamentos.get(indiceTabela);
            if(identificador == 1){
                tela.preencheEquipamento(equipamento);
            }else {
                tela.preencheTelaEquipamento(equipamento);
            }
        }
        limpaBuscarEquipamento();
        dispose();
    }//GEN-LAST:event_btSelecionarActionPerformed
    
    public Equipamento getEquipamento(){
        return equipamento;
    }
    
    //Metodo para limpeza dos campos da tela
    public void limpaBuscarEquipamento(){
        tfBuscaEquipamento.setText("");
        modelo.setRowCount(0);
    }
    
    public void indentificaTela(int identificador){
        this.identificador = identificador;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarEquipamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarEquipamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarEquipamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarEquipamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btSair;
    private javax.swing.JButton btSelecionar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbTituloDescricao;
    private javax.swing.JPanel pnTelaBuscaEquipamento;
    private javax.swing.JTable tbBuscaEquipamento;
    private javax.swing.JTextField tfBuscaEquipamento;
    // End of variables declaration//GEN-END:variables
}
